load("@rules_kotlin//kotlin:core.bzl", "define_kt_toolchain", "kt_javac_options", "kt_kotlinc_options")
load("@rules_python//python:py_binary.bzl", "py_binary")

package(default_visibility = ["//visibility:public"])
exports_files(["native_artifacts.bzl", "native_artifacts.py"])
kt_kotlinc_options(name = "kotlinc_options", jvm_target = "17", x_jvm_default = "all")
kt_javac_options(name = "javac_options", release = "17")
define_kt_toolchain(
    name = "kotlin_toolchain",
    language_version = "2.0",
    api_version = "2.0",
    jvm_target = "17",
    kotlinc_options = ":kotlinc_options",
    javac_options = ":javac_options",
    experimental_build_tools_api = False,
    jvm_stdlibs = ["@bridge_maven//:org_jetbrains_kotlin_kotlin_stdlib", "@rules_kotlin//kotlin/compiler:annotations"],
    jvm_runtime = ["@bridge_maven//:org_jetbrains_kotlin_kotlin_stdlib"],
)
py_binary(name = "bridge_artifacts", srcs = ["bridge_artifacts.py"])
py_binary(name = "test_suite", srcs = ["test_suite.py"])
exports_files(["nuget.bzl"])

exports_files(["Bridge.plist", "managed-test-main.cs"])

exports_files(["locks/bridge_maven_install.json"])

exports_files(["rules-kotlin-2.0-adapter.patch"])
